# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
## general purpose linting and formatting
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/codespell-project/codespell
  rev: v2.1.0
  hooks:
  - id: codespell
{% if cookiecutter.linting_support_for_python == "yes" %}
## Python support
- repo: https://github.com/psf/black
  rev: 21.9b0
  hooks:
  - id: black
- repo: https://gitlab.com/PyCQA/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    exclude: ^report/
- repo: https://github.com/timothycrosley/isort
  rev: 5.9.3
  hooks:
  - id: isort
{% endif %}
{% if cookiecutter.linting_support_for_snakemake == "yes" %}
## Snakemake linting
- repo: https://github.com/snakemake/snakefmt
  rev: 0.4.3
  hooks:
  - id: snakefmt
{% endif %}
{% if cookiecutter.linting_support_for_CPP == "yes" %}
## C++ support
- repo: https://gitlab.com/daverona/pre-commit/cpp
  rev: 0.8.0
  hooks:
  - id: clang-format
  - id: cpplint
    args: ["--includeorder=default"]
  - id: cppcheck
{% endif %}
{% if cookiecutter.linting_support_for_R == "yes" %}
## R support
- repo: https://github.com/lorenzwalthert/precommit
  rev: v0.1.3
  hooks:
  - id: style-files
  - id: parsable-R
  - id: no-browser-statement
  - id: lintr
    verbose: true
## Note: the following three hooks apply only to R package development
#  - id: roxygenize
#  - id: deps-in-desc
#  - id: use-tidy-description
{% endif %}
